vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - github.copilot
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - svelte.svelte-vscode
    - prisma.prisma
tasks:
  - init: npm install
    command: npm run dev
ports:
  - port: 3000
    onOpen: open-browser
