vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - github.copilot
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - svelte.svelte-vscode
    - prisma.prisma
tasks:
  - init: npm i -g @railway/cli
  - init: npm install
  - command: railway run npm run dev
    name: dev-server
  - command: railway run npx prisma studio
    name: db-ui
ports:
  - port: 3000
    onOpen: open-browser
    name: server
  - port: 5555
    onOpen: open-browser
    name: db
